### ISSUE TITLE
Build your first app – Code error (v.1.2.0)

### ISSUE THREAD

**Issue by tomaskuba** [serverpod/serverpod_docs#60]
Hi, I am just going through **"Build your first app"** tutorial, and I have an issue in the section [Fetch notes from the database](https://docs.serverpod.dev/tutorials/first-app#fetch-notes-from-the-database).

When I add the line `orderBy: Note.t.id,` I am getting an error `The argument type 'ColumnInt' can't be assigned to the parameter type 'Column<dynamic> Function(NoteTable)?'.`

I am not skilled enough in the Dart to hint at the solution, but the read operation results are ordered by ID by default.

**Comment by Isakdl** [comment]
This is wrong in the docs! We have just fixed this now but not deployed yet.

`orderBy` is a callback function now!

The code should look like this:
```dart
Note.db.find(
  ...,
  orderBy: (t) => t.id,
);
```

**Comment by Isakdl** [comment]
Fixed in: https://github.com/serverpod/serverpod_docs/pull/62

**Comment by SandPod** [comment]
The docs have now been updated on https://docs.serverpod.dev/tutorials/first-app
